apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: This is a basic catalog example that simply
      prints "hello argo!".
    workflows.argoproj.io/maintainer: '@alexec'
    workflows.argoproj.io/tags: example
    workflows.argoproj.io/version: '>= 2.9.0'
  name: echo
spec:
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.13
      command: [echo, "{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-diamond
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        templateRef: 
          name: echo
          template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        templateRef:
          name: echo
          template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        templateRef:
          name: echo
          template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        templateRef:
          name: echo
          template: echo
        arguments:
          parameters: [{name: message, value: D}]
